"""core_db_changes

Revision ID: 0cc3eabae5ce
Revises: 
Create Date: 2019-11-11 01:20:33.139329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc3eabae5ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_external_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_external_id')
    )
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('cluster_external_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_external_id')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ip_addr', sa.String(length=255), nullable=True),
    sa.Column('instance', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('cluster_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_info_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('tagged_machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tagged_machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identifier')
    op.drop_table('machine')
    op.drop_table('cluster')
    op.drop_table('users')
    # ### end Alembic commands ###
