"""datetime fields added

Revision ID: 10f6ee720750
Revises: 0cc3eabae5ce
Create Date: 2019-11-11 01:29:18.631257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f6ee720750'
down_revision = '0cc3eabae5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('cluster', sa.Column('DeletedAt', sa.DateTime(), nullable=True))
    op.add_column('cluster', sa.Column('ModifiedAt', sa.DateTime(), nullable=True))
    op.add_column('identifier', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('machine', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('machine', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'is_active')
    op.drop_column('machine', 'CreatedAt')
    op.drop_column('identifier', 'CreatedAt')
    op.drop_column('cluster', 'ModifiedAt')
    op.drop_column('cluster', 'DeletedAt')
    op.drop_column('cluster', 'CreatedAt')
    # ### end Alembic commands ###
